<?php require 'templates/elements/header.phtml'; ?>
<?php require 'templates/elements/menu.phtml'; ?>

<!-- Begin page content -->
<div class="container">

    <div class="mt-3">
        <h1><?= $title ?></h1>
    </div>

    <form method="POST" action="<?= PATH ?>admin/profiles/add" data-toggle="validator" role="form" id="formAdd">
        <div class="form-group">
            <label for="name">Descrição</label>
            <input type="text" class="form-control" id="description" aria-describedby="descriptionHelp"
                   name="description"
                   placeholder="Seu perfil aqui" value="<?= $profile->description ?>"
                   data-validetta="required,minLength[3],maxLength[50]">
            <small id="nameHelp" class="form-text text-muted">Escolhe um nome bem massa!</small>
        </div>

        <button type="submit" class="btn btn-primary" id="submit">Adicionar</button>
    </form>
</div>

<script>
    $('#formAdd').validetta({
        showErrorMessages: true,
        display: 'bubble',
        bubblePosition: 'bottom',
        realTime: true,
        onValid: function (e) {
            e.preventDefault();
            var load = isLoading({text: 'Aguarde...'});
            load.loading();

            var url = $("#formAdd").attr('action');

            $.ajax({
                type: "POST",
                url: url,
                data: $("#formAdd").serialize(),
                success: function (data) {

                    data = $.parseJSON(data);

                    if (data.type == "success") {
                        alertify.alert("CRUD Rochedo", data.message, function () {
                            document.location = "<?= PATH ?>admin/profiles";
                        });
                    } else {
                        if ($.trim(data.message) != undefined && $.trim(data.message) != "") {
                            alertify.notify(data.message, 'error', 5, function () {
                            });
                        } else {
                            $.each(data.errors, function (a, b) {
                                var message = "Erro: " + b;
                                alertify.notify(message, 'error', 5, function () {
                                });
                            });
                        }
                    }

                    isLoading().remove();

                },

                error: function (response) {
                    isLoading().remove();
                    var message = "Erro: " + response.statusText;
                    alertify.notify(message, 'error', 5, function () {
                    });
                }
            });


        }
    });
</script>

<?php require 'templates/elements/footer.phtml'; ?>

