<?php require 'templates/elements/header.phtml'; ?>
<?php require 'templates/elements/menu.phtml'; ?>


<link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">
<!-- Begin page content -->
<div class="container">
    <div class="mt-3">
        <h1 style="float:left"><?= $title ?></h1>
        <a style="float:RIGHT" class="btn btn-outline-success" href="<?= PATH ?>admin/profiles/add">Adicionar</a>
    </div>
</div>

<div class="container">
    <table class="table dataTable" id="tableProfiles">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Descrição</th>
            <th>Ações</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($profiles as $profile): ?>
            <tr>
                <th scope="row"><?= $profile['id_perfil'] ?></th>
                <td><?= utf8_encode($profile['descricao']) ?></td>
                <td>
                    <span class="btn-group" role="group" aria-label="Basic example">
                        <a href="<?= PATH ?>admin/profiles/edit/<?= $profile['id_perfil'] ?>" type="" class="btn btn-primary">Editar</a>
                        <a href="<?= PATH ?>admin/profiles/delete/<?= $profile['id_perfil'] ?>"
                           class="btn btn-danger delProfile">Excluir</a>
                    </span>
                </td>

            </tr>
        <?php endforeach; ?>

        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#tableProfiles').DataTable();
    });
    var temp = $(this);
    $(".delProfile").on('click', function (e) {
        e.preventDefault();
        var url = $(this).attr('href');
        var temp = $(this);

        alertify.confirm('CRUD Rochedo', 'Deseja excluir esse perfil?', function (e) {
            var url = temp.attr('href');

            var load = isLoading({text: 'Aguarde...'});
            load.loading();

            $.ajax({
                type: "GET",
                url: url,
                success: function (data) {

                    data = $.parseJSON(data);
                    console.log(data.message);

                    if (data.type == "success") {
                        alertify.alert("CRUD Rochedo", data.message, function () {
                            document.location = "<?= PATH ?>admin/profiles";
                        });
                    } else {
                        if ($.trim(data.message) != undefined && $.trim(data.message) != "") {
                            alertify.notify(data.message, 'error', 5, function () {
                            });
                        } else {
                            $.each(data.errors, function (a, b) {
                                var message = "Erro: " + b;
                                alertify.notify(message, 'error', 5, function () {
                                });
                            });
                        }
                    }

                    isLoading().remove();

                },

                error: function (response) {
                    isLoading().remove();
                    var message = "Erro: " + response.statusText;
                    alertify.notify(message, 'error', 5, function () {
                    });
                }
            });


        }, function () {
        });
    });
</script>

<?php require 'templates/elements/footer.phtml'; ?>

