<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="phmsanttos@gmail.com">

    <title><?= $title ?></title>


    <link href="<?= PATH ?>public/css/bootstrap/bootstrap.min.css" rel="stylesheet">
    <link href="<?= PATH ?>public/css/dataTable/dataTables.bootstrap4.min.css">
    <link href="<?= PATH ?>public/css/sticky-footer-navbar.css" rel="stylesheet">
    <link href="<?= PATH ?>public/css/validetta/validetta.min.css" rel="stylesheet">
    <link href="<?= PATH ?>public/css/isLoading/isLoading.min.css" rel="stylesheet">
    <link href="<?= PATH ?>public/css/alertify/alertify.min.css" rel="stylesheet">
    <link href="<?= PATH ?>public/css/alertify/themes/bootstrap.css" rel="stylesheet">

    <script src="<?= PATH ?>public/js/jquery-3.2.1.min.js"></script>
    <script src="<?= PATH ?>public/js/bootstrap/popper.min.js"></script>
    <script src="<?= PATH ?>public/js/bootstrap/bootstrap.min.js"></script>
    <script src="<?= PATH ?>public/js/bootstrap/ie10-viewport-bug-workaround.js"></script>
    <script src="<?= PATH ?>public/js/dataTable/jquery.dataTables.min.js"></script>
    <script src="<?= PATH ?>public/js/dataTable/dataTables.bootstrap4.min.js"></script>
    <script src="<?= PATH ?>public/js/validetta/validetta.min.js"></script>
    <script src="<?= PATH ?>public/js/validetta/validettaLang-pt-BR.js"></script>
    <script src="<?= PATH ?>public/js/isLoading/isLoading.min.js"></script>
    <script src="<?= PATH ?>public/js/inputMask/jquery.inputmask.bundle.js"></script>
    <script src="<?= PATH ?>public/js/alertify/alertify.min.js"></script>


    <script>
        alertify.defaults.transition = "slide";
        alertify.defaults.theme.ok = "btn btn-primary";
        alertify.defaults.theme.cancel = "btn btn-danger";
        alertify.defaults.theme.input = "form-control";
    </script>

</head>

<body>